### PR TITLE
Propagate Content-Type and Accept headers when using http

### LINKED ISSUE #17: Propagate Content-Type when using http.
Dispatcher contract should have access to payload + headers, whatever the way they were encoded

### PR DESCRIPTION
**Pull request by ericbottard**
Fixes #17

### CODE REVIEW

**Comment by markfisher** [comment]
seeing this when trying the "echo" sample:

```
panic: runtime error: index out of range
 goroutine 1 [running]:
main.main()
    /Users/mark/go/src/github.com/projectriff/function-sidecar/cmd/function-sidecar.go:75 +0xf93
```

**Comment by ericbottard** [comment]
`echo` worked fine for me.
```[echo-5974576769-c6pqk sidecar] Creating new stdio Dispatcher
[echo-5974576769-c6pqk sidecar] Created /pipes/input
[echo-5974576769-c6pqk sidecar] Created /pipes/output
[echo-5974576769-c6pqk sidecar] 2017/11/27 16:52:55 Rebalanced: &{Claimed:map[greetings:[0 1 2]] Released:map[] Current:map[greetings:[0 1 2]]}
[echo-5974576769-c6pqk sidecar] <<< Message{hello, map[Content-Type:text/plain Accept:*/*]}
[echo-5974576769-c6pqk sidecar] >>> Message{received: hello, map[]}
```

Will check gRPC

**Comment by markfisher** [comment]
yes, I am running with the latest `function-controller`

**Comment by ericbottard** [comment]
`uppercase` is fine as well (after fixes [here](https://github.com/projectriff/riff/pull/190))

**Comment by markfisher** [comment]
I am no longer seeing the `input` error (may have been a race between the function and topic yaml for the echo sample where those are 2 separate files), but I am seeing this consistently with this PR branch (and not seeing it as soon as I replace the docker image with the current `upstream/master`): ```Sidecar for function 'echo' (greetings->replies) using stdio dispatcher starting
Creating new stdio Dispatcher
panic: file exists
 goroutine 1 [running]:
github.com/projectriff/function-sidecar/pkg/dispatcher/stdio.NewStdioDispatcher(0xc420039bf0, 0x43477b)
    /Users/mark/go/src/github.com/projectriff/function-sidecar/pkg/dispatcher/stdio/stdio.go:63 +0x525
main.createDispatcher(0x7ffe6a9357ab, 0x5, 0xc4201f4180, 0x7ffe6a93579b)
    /Users/mark/go/src/github.com/projectriff/function-sidecar/cmd/function-sidecar.go:170 +0x71
main.main()
    /Users/mark/go/src/github.com/projectriff/function-sidecar/cmd/function-sidecar.go:110 +0x361```

**Comment by markfisher** [comment]
squashed and merged as https://github.com/projectriff/function-sidecar/commit/2f71ca3d55da0efe109a62b9b14ad5bc93101eb0

**Pull request closed without merging**
